-- Challenge - Joining on multiple tables
USE sakila;

-- 1. List the number of films per category.
SELECT category_id,name,COUNT(film_id) AS 'Nember of films'
FROM film f
JOIN film_category fc USING (film_id)
JOIN category USING (category_id)
GROUP BY category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT DISTINCT(store_id),city,country
FROM store s
JOIN address USING(address_id)
JOIN city USING (city_id)
JOIN country USING (country_id)
GROUP BY (store_id);

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT store_id,SUM(amount) AS 'total revenue'
FROM store S
JOIN staff USING (store_id)
JOIN payment USING (staff_id)
GROUP BY (store_id);

-- 4. Determine the average running time of films for each category.
SELECT name, ROUND(AVG(length),0) AS 'Ave running time'
FROM film f
JOIN film_category fc USING(film_id)
JOIN category c USING(category_id)
GROUP BY (category_id);

-- Bonus:
-- 5. Identify the film categories with the longest average running time.
SELECT name, ROUND(AVG(length),0) AS 'Ave running time'
FROM film f
JOIN film_category fc USING(film_id)
JOIN category c USING(category_id)
GROUP BY (category_id)
ORDER BY ROUND(AVG(length),0) DESC
LIMIT 1;
